version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: mockly-postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s # 5초마다 체크
      timeout: 5s # 5초 내 응답 없으면 실패
      retries: 5 # 5번 실패 시 unhealthy
    networks:
      - mockly-network

  redis:
    image: redis:7-alpine
    container_name: mockly-redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - mockly-network
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5


  app:
    build:
      context: . # 현재 디렉토리
      dockerfile: Dockerfile
    container_name: mockly-server
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy # POSTGRES가 healthy일 때만 시작
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_ANDROID_CLIENT_ID: ${GOOGLE_ANDROID_CLIENT_ID}
    ports:
      - "8080:8080"
    networks:
      - mockly-network

volumes:
  postgres_data:
  redis_data:

networks:
  mockly-network:
    driver: bridge